package dj.plug.plugdj.socket

object Events {
  val ACK = "ack"
  val ADVANCE = "advance"
  val BAN = "ban"
  val CHAT = "chat"
  val CHAT_DELETE = "chatDelete"
  val DJ_LIST_CYCLE = "djListCycle"
  val DJ_LIST_LOCKED = "djListLocked"
  val DJ_LIST_UPDATE = "djListUpdate"
  val EARN = "earn"
  val FLOOD_API = "floodAPI"
  val FLOOD_CHAT = "floodChat"
  val FRIEND_ACCEPT = "friendAccept"
  val FRIEND_REQUEST = "friendRequest"
  val GIFTED = "gifted"
  val GRAB = "grab"
  val KILL_SESSION = "killSession"
  val LEVEL_UP = "levelUp"
  val MOD_ADD_DJ = "modAddDJ"
  val MOD_BAN = "modBan"
  val MOD_MOVE_DJ = "modMoveDJ"
  val MOD_MUTE = "modMute"
  val MOD_REMOVE_DJ = "modRemoveDJ"
  val MOD_SKIP = "modSkip"
  val MOD_STAFF = "modStaff"
  val NAME_CHANGED = "nameChanged"
  val NOTIFY = "notify"
  val PLAYLIST_CYCLE = "playlistCycle"
  val PLUG_MAINTENANCE = "plugMaintenance"
  val PLUG_MAINTENANCE_ALERT = "plugMaintenanceAlert"
  val PLUG_MESSAGE = "plugMessage"
  val RATE_LIMIT = "rateLimit"
  val ROOM_DESCRIPTION = "roomDescription"
  val ROOM_MIN_CHAT_LEVEL_UPDATE = "roomMinChatLevelUpdate"
  val ROOM_NAME_UPDATE = "roomNameUpdate"
  val ROOM_WELCOME_UPDATE = "roomWelcomeUpdate"
  val SKIP = "skip"
  val USER_JOIN = "userJoin"
  val USER_LEAVE = "userLeave"
  val USER_UPDATE = "userUpdate"
  val VOTE = "vote"
}
